### ISSUE TITLE
Incorrect promise handling upon Blake2b.ready

### ISSUE THREAD

**Issue by ozuchi** [mafintosh/blake2b-wasm#11]
At file and line: https://github.com/mafintosh/blake2b-wasm/blob/06317fe0d6e1a8ae34fc34cc1b8c76cfa935fecb/index.js#L103-L110

The promise handling seems to be inverted. Expected it to be following instead:

```js
  // backwards compat, can be removed in a new major
  var p = new Promise(function (reject, resolve) {
    wasm.onload(function (err) {
      if (!err) resolve()
      else reject()
      cb(err)
    })
  })
```

**Comment by jeffwalsh** [comment]
I am getting this same error in a chrome extension. I am using a module that uses the blake2wb-wasm module. Is there any way to resolve/supress this?

**Comment by mafintosh** [comment]
@jeffwalsh on latest version 2.3.0? what specific error are you getting?
