### ISSUE TITLE
memory.set RangeError: Source is too large

### ISSUE THREAD

**Issue by tonybart1337** [mafintosh/blake2b-wasm#2]
Hello and thanks for the great lib.

Currently there is a limit for an update chunk and it's **655080** bytes.

_memory.buffer_ **655360** bytes and _head_ is **64**, after initialization it's **280 (216 + 64)**, which leaves us with **655080** bytes to update.

Why is that so? Could you please elaborate?

**Comment by emilbayes** [comment]
This should be fixed now, right?

https://github.com/mafintosh/blake2b-wasm/blob/c7cf5f7d63cbd59e683571a2a4c133edbfeda31d/index.js#L64-L65

**Comment by mafintosh** [comment]
yep pretty sure this is fixed
