### ISSUE TITLE
Project requiring 8 byte hash

### ISSUE THREAD

**Issue by arosolino** [mafintosh/blake2b-wasm#3]
I am working on project that requires the length of my blake2b hash to be 8 bytes. Unfortunately this is not supported since BYTES_MIN = 16.

I noticed if I change this line from 16 to 8 like works as I need it to.

```js
var BYTES_MIN = module.exports.BYTES_MIN = 8
```

Is there any implications in me doing this, and why was 16 chosen.

Thanks

**Comment by arosolino** [comment]
I just noticed there is a noAssert flag.

**Comment by mafintosh** [comment]
Forcing it to generate an 8 byte hash isn't a great idea. You prob loose some of the cryptographic guarantees by doing that. For an 8 byte hash see https://github.com/mafintosh/siphash24
